---
title: Sujon from Dhaka
baseurl: ""
desc: Works | Learnings | Thoughts.
about: I am a problem solver, software engineer currently working at Escenic AS (Subsidiary of CCI Europe A/S) and living in Dhaka.
image: images/sujon.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugins:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
